"""Add project_id to Note model

Revision ID: xyz123abc456
Revises: 01936c97c038
Create Date: 2025-01-23 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'xyz123abc456'
down_revision: Union[str, None] = 'bb196eb3f4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_notes_project_id',
        'notes',
        'projects',
        ['project_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notes_project_id', 'notes', type_='foreignkey')
    op.drop_column('notes', 'project_id')
    # ### end Alembic commands ###

