"""Add color field to Project model

Revision ID: 01936c97c038
Revises: 14bed50e0a0b
Create Date: 2025-05-20 12:43:13.578590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01936c97c038'
down_revision: Union[str, None] = '14bed50e0a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'color')
    # ### end Alembic commands ###
