"""Add base_load_hours_per_week to User model

Revision ID: add_base_load_to_user
Revises: 01936c97c038
Create Date: 2026-02-12 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_base_load_to_user'
down_revision: Union[str, None] = '01936c97c038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('base_load_hours_per_week', sa.Float(), nullable=True, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'base_load_hours_per_week')
    # ### end Alembic commands ###
