"""update task status history model

Revision ID: bb196eb3f4dc
Revises: 01936c97c038
Create Date: 2025-05-21 20:21:31.009245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb196eb3f4dc'
down_revision: Union[str, None] = '01936c97c038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_status_history', sa.Column('changed_at', sa.DateTime(), nullable=False))
    op.add_column('task_status_history', sa.Column('changed_by', sa.Integer(), nullable=True))
    op.drop_index('ix_task_status_history_timestamp', table_name='task_status_history')
    op.create_index(op.f('ix_task_status_history_changed_at'), 'task_status_history', ['changed_at'], unique=False)
    op.create_foreign_key(None, 'task_status_history', 'users', ['changed_by'], ['id'])
    op.drop_column('task_status_history', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_status_history', sa.Column('timestamp', sa.DATETIME(), nullable=False))
    op.drop_constraint(None, 'task_status_history', type_='foreignkey')
    op.drop_index(op.f('ix_task_status_history_changed_at'), table_name='task_status_history')
    op.create_index('ix_task_status_history_timestamp', 'task_status_history', ['timestamp'], unique=False)
    op.drop_column('task_status_history', 'changed_by')
    op.drop_column('task_status_history', 'changed_at')
    # ### end Alembic commands ###
